print("Press enter to continue.")
print("         ----------------Welcome to the supermarket----------------")
print("1. View items")
print("2. Add items for sale")
print("3. Purchase items")
print("4. Search items")
print("5. Edit items")
print("6. Exit")
print("Enter the number of your choice : ", end="")
